////////////////////////////////////////
// Self Destroy
////////////////////////////////////////

IF
	Die()
THEN
	RESPONSE #100
		CreateVisualEffectObject("SPFLESHS",Myself)
		DestroySelf()
END

IF
	Allegiance(Myself,ENEMY)
	!Detect(NearestEnemyOf(Myself))
	!Detect(Player1)
	!Detect(Player2)
	!Detect(Player3)
	!Detect(Player4)
	!Detect(Player5)
	!Detect(Player6)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END
